Chapter3Project/Models/Member.cs
using System.ComponentModel.DataAnnotations.Schema;
using System.ComponentModel.DataAnnotations;

namespace Chapter3Project.Models
{
    public class Member
    {
        [Key]
        public int Id { get; set; }

        [Required(ErrorMessage = "Please enter your first name.")]
        [RegularExpression("^[a-zA-Z]*$", ErrorMessage = "Only Letters are allowed.")]
        [StringLength(15, ErrorMessage = "Please enter your first name in the 15 character limit.")]
        [Display(Name = "First Name")]
        [Column("FirstName")]
        public string FirstName { get; set; } = string.Empty;

        [StringLength(20, ErrorMessage = "Please enter your last name in the 20 character limit.")]
        [RegularExpression("^[a-zA-Z]*$", ErrorMessage = "Only Letters are allowed.")]
        [Display(Name = "Last Name")]
        [Column("LastName")]
        public string LastName { get; set; } = string.Empty;

        [Display(Name = "Favorite Smiski")]
        public string SetName { get; set; } = string.Empty;
    }
}

Chapter3Project/Models/Set.cs
using System.ComponentModel.DataAnnotations;

namespace Chapter3Project.Models
{
    public class Set
    {
        [Key]
        public string Id { get; set; } = string.Empty;

        [RegularExpression("^[a-zA-Z]*$", ErrorMessage = "Only Letters are allowed.")]
        [StringLength(20, ErrorMessage = "That set name is too long!")]
        [Required(ErrorMessage = "Please enter set name.")]
        [Display(Name ="Set Name")]
        public string SetName { get; set; } = string.Empty;

        [RegularExpression("^[a-zA-Z]*$", ErrorMessage = "Only Letters are allowed.")]
        [StringLength(30, ErrorMessage = "That pose name is too long!")]
        [Required(ErrorMessage = "Please enter pose for Smiski.")]
        [Display(Name = "Smiski Pose")]
        public string SmiskiType { get; set; } = string.Empty;

    }
}

Chapter3Project/Models/SetContext.cs
using Microsoft.EntityFrameworkCore;
using Chapter3Project.Models;

namespace Chapter3Project.Models
{
    public class SetContext : DbContext
    {
        public SetContext(DbContextOptions<SetContext> options) : base(options) { }

        public DbSet<Set> sets { get; set; } = null!;
        public DbSet<Member> Members { get; set; } = null!;
        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<Set>().HasData(
                 new Set
                 {
                     Id = "M",
                     SetName = "Moving",
                     SmiskiType ="Boxes Smiski"
                 },
                 new Set
                 {
                     Id = "D",
                     SetName = "Dressing",
                     SmiskiType = "Sweater Smiski"
                 },
                new Set
                {
                    Id = "B",
                    SetName = "Bath",
                    SmiskiType = "Shower Smiski"
                },
                new Set
                {
                    Id = "Y",
                    SetName = "Yoga",
                    SmiskiType = "Grounded Smiski"
                },
                new Set
                {
                    Id = "E",
                    SetName = "Exercise",
                    SmiskiType = "Sit Ups Smiski"
                },
                new Set
                {
                    Id = "C",
                    SetName = "Cheer",
                    SmiskiType = "Pom Pom Smiski"
                },
                new Set
                {
                    Id = "W",
                    SetName = "Work",
                    SmiskiType = "Laptop Smiski"
                },
                new Set
                {
                    Id = "L",
                    SetName = "Living",
                    SmiskiType = "Flute Smiski"
                }
             );
        }
    }
}

Chapter3Project/Controllers/SetController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Chapter3Project.Models;

namespace Chapter3Project.Controllers
{
    public class SetController : Controller
    {
        private readonly SetContext _context;

        public SetController(SetContext context)
        {
            _context = context;
        }

        // GET: Set
        public async Task<IActionResult> Index()
        {
            return View(await _context.sets.ToListAsync());
        }

        // GET: Set/Details/5
        public async Task<IActionResult> Details(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var @set = await _context.sets
                .FirstOrDefaultAsync(m => m.Id == id);
            if (@set == null)
            {
                return NotFound();
            }

            return View(@set);
        }

        // GET: Set/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Set/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,SetName,SmiskiType")] Set @set)
        {
            if (ModelState.IsValid)
            {
                _context.Add(@set);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(@set);
        }

        // GET: Set/Edit/5
        public async Task<IActionResult> Edit(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var @set = await _context.sets.FindAsync(id);
            if (@set == null)
            {
                return NotFound();
            }
            return View(@set);
        }

        // POST: Set/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(string id, [Bind("Id,SetName,SmiskiType")] Set @set)
        {
            if (id != @set.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(@set);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!SetExists(@set.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(@set);
        }

        // GET: Set/Delete/5
        public async Task<IActionResult> Delete(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var @set = await _context.sets
                .FirstOrDefaultAsync(m => m.Id == id);
            if (@set == null)
            {
                return NotFound();
            }

            return View(@set);
        }

        // POST: Set/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(string id)
        {
            var @set = await _context.sets.FindAsync(id);
            if (@set != null)
            {
                _context.sets.Remove(@set);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool SetExists(string id)
        {
            return _context.sets.Any(e => e.Id == id);
        }
    }
}

Chapter3Project/Views/Home/About.cshtml
@{
    ViewData["Title"] = "Smiski Fan Club";
}
<body style="background-color:cornsilk;">
<link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
<div class="p-3 ms-0 mb-2 shadow" style="background-color:darkolivegreen;border-radius:15px;text-align:center;">
    <h2>
        Smiski Fan Club
        <i class="material-icons" style="font-size:24px;">group</i>
    </h2>
</div>
<div class="p-5 ms-4 me-4">
    <img src="~/Images/smiskiLaptop.png" alt="smiski laptop" asp-append-version="true" class="float-start" img-fluid style="float:left;padding:10px;" />
    <h3>
        Our Purpose
    </h3>
    <p>
        Our goal is to connect Smiski fans far and wide. We strive to build a community that loves and cherishes Smiski's adventures as much as we do. Who is as nonchalant as Smiski? No one is. Our goal is to spread the Smiski way to souls who need it. 
    </p>
    <h3>
        Our Community
    </h3>
    <p>
        Our community loves Smiski. We bond through Smiski and share his different adventures. 
    </p>
    <h3>
        Our Love
    </h3>
    <p>
        We love Smiski.
    </p>
</div>
</body>

Chapter3Project/Views/Home/Contact.cshtml
@{
    ViewData["Title"] = "Smiski Fan Club";
}
<body style="background-color:cornsilk;">
<link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
<div class="p-3 ms-0 mb-2 shadow" style="background-color:darkolivegreen;border-radius:15px;text-align:center;">
    <h2>
        Smiski Fan Club
        <i class="material-icons" style="font-size:24px;">group</i>
    </h2>
</div>
<div class="ms-3">
    <h3 style="text-align:center">He is the best</h3>
    <img src="~/Images/smiskiSleepy.png" alt="smiski sleep" asp-append-version="true" class="float-end" img-fluid style="float:left;padding:10px;" />
    <p>Our Location:</p>
    <address>
        101 Smiski Avenue<br />
        Smiski City, MI 11234<br />
    </address>

    <address>
        <strong>Discord:</strong>   <a href="https://fdsfsdfg.com">SMISKI4LIFE</a><br />
        <strong>Email Us:</strong> <a href="mailto:SmiskiClubRep@Smiski.com">SmiskiClubRep@Smiski.com</a>
    </address>
</div>
</body>

Chapter3Project/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}
<body style="background-color:cornsilk;">
<div class="text-center">
    <h1 class="display-4" style="background-color:darkolivegreen;border-radius:15px;text-align:center;">Welcome to the Smiski Fan Club!</h1>
    <p>Just a little guy living a big life</p>
    <div class="col-4 p-5" >
        <img src="~/Images/smiskiClothes.png" alt="smiski clothes" asp-append-version="true" class="float-start p-4" style="height: 400px; width:600px;" />
    </div>
    <h3>Who is Smiski</h3>
    <p>Smiski is not only a guy, he is a lifestyle. His many adventures of putting on pants, sitting on the ground, teaching a cless, taking a shower, sitting on the ground again really represents humanity. We all strive to be like Smiski.</p>
</div>
</body>

Chapter3Project/Views/Set/Create.cshtml
@model Chapter3Project.Models.Set

@{
    ViewData["Title"] = "Create";
}
<body style="background-color:cornsilk;">
<h1>Create</h1>

<h4 style="background-color:darkolivegreen;border-radius:15px;text-align:center;">Set</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
<<<<<<< HEAD
                <label asp-for="Id" class="control-label"></label>
                <input asp-for="Id" class="form-control" />
                <span asp-validation-for="Id" class="text-danger"></span>
=======
                <label asp-for="SetId" class="control-label"></label>
                <input asp-for="SetId" class="form-control" />
                <span asp-validation-for="SetId" class="text-danger"></span>
>>>>>>> 38fd506ac25a0ac1cf776421c104b3bdd297ec7b
            </div>
            <div class="form-group">
                <label asp-for="SetName" class="control-label"></label>
                <input asp-for="SetName" class="form-control" />
                <span asp-validation-for="SetName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="SmiskiType" class="control-label"></label>
                <input asp-for="SmiskiType" class="form-control" />
                <span asp-validation-for="SmiskiType" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}
</body>

Chapter3Project/Views/Set/Delete.cshtml
@model Chapter3Project.Models.Set

@{
    ViewData["Title"] = "Delete";
}
<body style="background-color:cornsilk;">
<h1 style="background-color:darkolivegreen;border-radius:15px;text-align:center;">Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.SetName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.SetName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.SmiskiType)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.SmiskiType)
        </dd>
    </dl>
    
    <form asp-action="Delete">
<<<<<<< HEAD
        <input type="hidden" asp-for="Id" />
=======
        <input type="hidden" asp-for="SetId" />
>>>>>>> 38fd506ac25a0ac1cf776421c104b3bdd297ec7b
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>
</body>

Chapter3Project/Views/Set/Details.cshtml
@model Chapter3Project.Models.Set

@{
    ViewData["Title"] = "Details";
}
<body style="background-color:cornsilk;">
<h1 style="background-color:darkolivegreen;border-radius:15px;text-align:center;">Details</h1>

<div>
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.SetName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.SetName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.SmiskiType)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.SmiskiType)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>
</body>

Chapter3Project/Views/Set/Edit.cshtml
@model Chapter3Project.Models.Set

@{
    ViewData["Title"] = "Edit";
}
<body style="background-color:cornsilk;">
<h1 style="background-color:darkolivegreen;border-radius:15px;text-align:center;">Edit</h1>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
<<<<<<< HEAD
            <input type="hidden" asp-for="Id" />
=======
            <input type="hidden" asp-for="SetId" />
>>>>>>> 38fd506ac25a0ac1cf776421c104b3bdd297ec7b
            <div class="form-group">
                <label asp-for="SetName" class="control-label"></label>
                <input asp-for="SetName" class="form-control" />
                <span asp-validation-for="SetName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="SmiskiType" class="control-label"></label>
                <input asp-for="SmiskiType" class="form-control" />
                <span asp-validation-for="SmiskiType" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}
</body>

Chapter3Project/Views/Set/Index.cshtml
@model IEnumerable<Chapter3Project.Models.Set>

@{
    ViewData["Title"] = "Index";
}
<body style="background-color:cornsilk;">
<h1 style="background-color:darkolivegreen;border-radius:15px;text-align:center; margin-bottom:15px;">Index</h1>

<p style="text-align:center;">
    <a asp-action="Create" style=" color: antiquewhite;border-radius: 3px; background-color:burlywood;padding:5px;">Create New</a>
</p>
<table class="table table-striped">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.SetName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.SmiskiType)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.SetName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.SmiskiType)
            </td>
            <td>
                        <a asp-action="Edit" asp-route-id="@item.Id" style="color:black;">Edit</a> |
                        <a asp-action="Details" asp-route-id="@item.Id" style="color:black;">Details</a> |
                        <a asp-action="Delete" asp-route-id="@item.Id" style="color:black;">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>
</body>

Chapter3Project/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Smiski Fan Club</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/layout.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Chapter3Project.styles.css" asp-append-version="true" />
</head>
<body style="background-color:cornsilk;">
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand text-dark" asp-area="" asp-controller="Home" asp-action="Index">Smiski Fan Club</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Set" asp-action="Index">Set List</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="About">About</a>
                        </li>
                        @*<li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Member" asp-action="Index">Members</a>
                        </li>*@
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Contact">Contact</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - Chapter3Project - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>